/**
 * Asset manifest types for the preloading system.
 * Generated by scripts/generate-asset-manifest.js
 */

/** Image assets organized by difficulty/state */
export interface ImagesByDifficulty {
  easy: string[];
  medium: string[];
  hard: string[];
}

/** End screen images by result type */
export interface EndImages {
  victory: string[];
  retreat: string[];
  defeat: string[];
}

/** Campaign-specific assets */
export interface CampaignAssets {
  /** Level 1.1: Loaded when campaign button is pressed */
  level1_1: {
    /** Campaign background music */
    music: string | null;
    /** Alternative music path */
    musicAlt: string | null;
    /** Play screen images for easy difficulty */
    playImages: {
      easy: string[];
    };
  };
  /** Level 2: Loaded during gameplay */
  level2: {
    /** Play screen images for medium/hard */
    playImages: {
      medium: string[];
      hard: string[];
    };
    /** End screen images per result */
    endImages: EndImages;
  };
}

/** Game-specific assets in the manifest */
export interface GameAssets {
  /** Assets for GameSelector cards */
  cardAssets: {
    gameCard: string | null;
    favicon: string | null;
  };
  /** Level 1: StartScreen assets */
  level1: {
    icons: string[];
    sounds: string[];
    mainMenuMusic: string | null;
    startImages: string[];
    campaignStartImages: Record<string, string[]>;
  };
  /** Level 2: End game assets */
  level2: {
    defeatMusic: string | null;
    victoryMusic: string | null;
    retreatMusic: string | null;
    endImages: EndImages;
  };
  /** Voice lines for companions */
  voices: string[];
  /** Campaign-specific assets */
  campaigns: Record<string, CampaignAssets>;
}

/** Engine-level assets */
export interface EngineAssets {
  icons: string[];
  images: string[];
  sounds: string[];
}

/** Complete asset manifest structure */
export interface AssetManifest {
  version: string;
  engine: EngineAssets;
  games: Record<string, GameAssets>;
}

/** Loading levels for the preloading system */
export type LoadLevel =
  | 'level0'     // GameSelector: engine + game cards
  | 'level1'     // Game selected: StartScreen assets
  | 'level1_1'   // Campaign selected: campaign assets (background)
  | 'level2';    // In-game: remaining assets (background)

/** Progress callback for asset loading */
export type ProgressCallback = (loaded: number, total: number) => void;
