export {
  getBasePath,
  withBasePath,
  publicFile,
  publicDir,
  gameDir,
  gameFile,
  gameIconsDir,
  gameIconsFile,
  gameFaviconDir,
  gameFaviconFile,
  gameImagesDir,
  gameImagesFile,
  type GamePublicDir,
} from '@app/utils/paths';
