// Auto-generated by scripts/generate-game-registry.js.
// Do not edit manually.

import type { GameRegistry } from '@app/types';

export const GAME_REGISTRY_INDEX: GameRegistry[] = [
  {
    "id": "axis",
    "visible": true,
    "available": true,
    "title": "AXIS",
    "emoji": "🧭",
    "theme": {
      "isLight": false,
      "bgFrom": "#020617",
      "bgVia": "#0b1b34",
      "bgTo": "#05070f",
      "glow": "#38bdf8"
    }
  },
  {
    "id": "bg3",
    "visible": true,
    "available": true,
    "title": "BALDUR'S GATE III",
    "emoji": "⚔️",
    "theme": {
      "isLight": false,
      "bgFrom": "#000000",
      "bgVia": "#3b2416",
      "bgTo": "#000000",
      "glow": "#fbbf24"
    }
  },
  {
    "id": "nnr",
    "visible": true,
    "available": true,
    "title": "НЕЙРОСЕТИ В РАДИОЛОКАЦИИ",
    "emoji": "🧠",
    "theme": {
      "isLight": false,
      "bgFrom": "#041815",
      "bgVia": "#063647",
      "bgTo": "#02060c",
      "glow": "#63D792"
    }
  },
  {
    "id": "poc",
    "visible": true,
    "available": true,
    "title": "PROOF OF CONCEPT",
    "emoji": "⚙️",
    "theme": {
      "isLight": false,
      "bgFrom": "#000000",
      "bgVia": "#4338ca",
      "bgTo": "#000000",
      "glow": "#6366f1"
    }
  },
  {
    "id": "sky-cotl",
    "visible": true,
    "available": true,
    "title": "SKY",
    "emoji": "☁️",
    "theme": {
      "isLight": true,
      "bgFrom": "#ffffff",
      "bgVia": "#00aaff",
      "bgTo": "#ffffff",
      "glow": "#fbbf24"
    }
  },
  {
    "id": "transformers",
    "visible": true,
    "available": true,
    "title": "TRANSFORMERS",
    "emoji": "🤖",
    "theme": {
      "isLight": false,
      "bgFrom": "#09090b",
      "bgVia": "#09090b",
      "bgTo": "#000000",
      "glow": "#dc2626"
    }
  }
];
